timeout: 1800s

steps:
- name: launcher.gcr.io/google/debian11
  id: efi-stub
  args:
  - build/build-efi-stub.sh
  entrypoint: /bin/bash
  waitFor: ['-']
- name: launcher.gcr.io/google/debian11
  id: linux
  args:
  - linux/build.sh
  entrypoint: /bin/bash
  waitFor: ['-']
- name: gcr.io/cloud-builders/go:1.18
  id: init
  args:
  - init/build.sh
  entrypoint: /bin/sh
  waitFor: ['efi-stub']
- name: gcr.io/cloud-builders/go:1.18
  id: caaos
  args:
  - services/caaos/build.sh
  entrypoint: /bin/sh
  waitFor: ['efi-stub']
- name: gcr.io/cloud-builders/go:1.17
  id: containerd
  args:
  - services/containerd/build.sh
  entrypoint: /bin/sh
  waitFor: ['efi-stub']
- name: gcr.io/cloud-builders/go:1.18
  id: otelopscol
  args:
  - caaos/otelopscol/build.sh
  entrypoint: /bin/sh
  waitFor: ['efi-stub']
- name: gcr.io/cloud-builders/go:1.18
  id: google-osconfig-agent
  args:
  - caaos/google-osconfig-agent/build.sh
  entrypoint: /bin/sh
  waitFor: ['efi-stub']
- name: gcr.io/cloud-builders/go:1.18
  id: hello-world
  args:
  - caaos/hello-world/build.sh
  entrypoint: /bin/sh
  waitFor: ['efi-stub']
- name: gcr.io/cloud-builders/go:1.18
  id: daisy
  args:
  - build/build-daisy.sh
  entrypoint: /bin/sh
  waitFor: ['efi-stub']
- name: launcher.gcr.io/google/debian11
  id: sbkeys
  args:
  - build/generate-sbkeys.sh
  entrypoint: /bin/bash
  waitFor: ['efi-stub']
- name: launcher.gcr.io/google/debian11
  id: image
  entrypoint: /bin/bash
  args:
  - build/build-image.sh
  env:
  - ZONE=us-central1-a
  - PUBLISH_PROJECT=${PROJECT_ID}
  - GCS_ROOT=${_GCS_ROOT}
  - IMAGE_OUTPUT_BUCKET=${_IMAGE_OUTPUT_BUCKET}
  - KERNEL_PACKAGE=${_KERNEL_PACKAGE}
  - PACKAGES=${_PACKAGES}
options:
  dynamic_substitutions: true
  machineType: 'E2_HIGHCPU_32'
  diskSizeGb: '500'
  env:
  - GOPROXY=https://proxy.golang.org
  - GOAMD64=v3
substitutions:
  _GCS_ROOT: ${PROJECT_ID}/ecl
  _IMAGE_OUTPUT_BUCKET: ${PROJECT_ID}/ecl/images
  _KERNEL_PACKAGE: kernel.tar.gz
  _PACKAGES: "containerd.tar.gz init.tar.gz caaos.tar.gz otelopscol.tar.gz google-osconfig-agent.tar.gz hello-world.tar.gz"