steps:
- name: gcr.io/cloud-builders/go:1.17
  id: otelopscol
  args:
  - caaos/otelopscol/build.sh
  entrypoint: /bin/sh
- name: gcr.io/cloud-builders/go:1.17
  id: google-osconfig-agent
  args:
  - caaos/google-osconfig-agent/build.sh
  entrypoint: /bin/sh
options:
  dynamic_substitutions: true
  machineType: 'E2_HIGHCPU_8'
  env:
  - GOPROXY=https://proxy.golang.org
artifacts:
  objects:
    location: gs://${_PACKAGE_BUCKET}
    paths: [caaos/otelopscol/otelopscol.tar.gz, caaos/google-osconfig-agent/google-osconfig-agent.tar.gz, caaos/hello-world/hello-world.tar.gz]
substitutions:
    _PACKAGE_BUCKET: ${PROJECT_ID}/ecl