timeout: 1800s

steps:
- name: launcher.gcr.io/google/debian11
  args:
  - linux/build.sh
  entrypoint: /bin/bash
options:
  dynamic_substitutions: true
  machineType: 'E2_HIGHCPU_32'
artifacts:
  objects:
    location: gs://${_PACKAGE_BUCKET}
    paths: [kernel.tar.gz]
substitutions:
    _PACKAGE_BUCKET: ${PROJECT_ID}/ecl